spring:
  application:
    name: vk-test-task

remote:
  server:
    baseUrl: https://jsonplaceholder.typicode.com/

springdoc:
  swagger-ui:
    path=/swagger-ui-custom:
      html: /swagger-ui.html
